### ISSUE TITLE
Thanks a lot!

### ISSUE THREAD

**Issue by matheo** [jsvalley/ng2-map#1]
Keep it up Allen
Awesome stuff :+1: 
Thanks!!!

**Comment by allenhwkim** [comment]
No problem, more will to come soon.

Looking for a collaborator too. Are you interested in?

**Comment by matheo** [comment]
I will test and provide feedback
still learning Angular 2 and Javascript powers ;)

**Comment by aitboudad** [comment]
@allenhwkim I'm interested, please add me to the repo!

**Comment by allenhwkim** [comment]
@aitboudad
Thanks, you are already a cintrubutor:)
I will add you as a collaborator immediately after seeing a quality commit, e.g., shape directive, layer directive etc.
